### ISSUE TITLE
What is the recommended amxx version

### ISSUE THREAD

**Issue by tarimren-admin** [mrglaster/AMX-Plugins-Translator#1]
Hello, I like this way of implementing multiple languages, but the 1.8.2 version is not supported well. What is the recommended version of amxx?

**Comment by mrglaster** [comment]
>  but the 1.8.2 version is not supported well.

Hello! During the  debug I used plugins for  the current latest version (1.9.0), so I can't say for sure starting from which version of AMX there will definitely be no problems.

Can you send me the plugin you try  to  translate? Which lines are the problem  for the utility?  In any case, I will try to fix the problem if it's possible. 

Thanks for pointing out this issue!

**Comment by tarimren-admin** [comment]
I am from China and reported an error when trying to translate the plug-in. The operation information is as follows:
C:\AMX-Plugins-Translator.1.2>AMX-Plugins-Translator.exe server_menu_public.sma ru "cn,en"
cn

Detected 2 Languages: cn, en
Problems not found!
Replacing plugin's hardcoded strings to Dictionary References
Generating Dictionary Key for line:  menuIdHandler
Unhandled exception. System.AggregateException: One or more errors occurred. (No translator provided a valid result. (由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.googleapis.com:443)) (由于连接方在一 段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.google.com:443)) (The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.) (The SSL connection could not be established, see inner exception.) (The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.))
 ---> System.AggregateException: No translator provided a valid result. (由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.googleapis.com:443)) (由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.google.com:443)) (The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.) (The SSL connection could not be established, see inner exception.) (The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.googleapis.com:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GTranslate.Translators.GoogleTranslator.TranslateAsync(String text, ILanguage toLanguage, ILanguage fromLanguage)
   at GTranslate.Translators.GoogleTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.GoogleTranslator.GTranslate.Translators.ITranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   --- End of inner exception stack trace ---
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at DictionaryGenerator.modules.TextTranslator.processTranslationApi(String sourceText, String outputLang) in C:\Users\mrglaster\Desktop\AMX-Plugins-Translator-main\AMX-Plugins-Translator\modules\TextTranslator.cs:line 43
 ---> (Inner Exception #1) System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (translate.google.com:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GTranslate.Translators.GoogleTranslator2.SendAndParseResponseAsync(HttpRequestMessage request)
   at GTranslate.Translators.GoogleTranslator2.TranslateAsync(String text, ILanguage toLanguage, ILanguage fromLanguage)
   at GTranslate.Translators.GoogleTranslator2.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.GoogleTranslator2.GTranslate.Translators.ITranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)<---

 ---> (Inner Exception #2) System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at GTranslate.Translators.MicrosoftTranslator.GetOrUpdateMicrosoftAuthTokenAsync()
   at GTranslate.Translators.MicrosoftTranslator.TranslateAsync(String text, ILanguage toLanguage, ILanguage fromLanguage)
   at GTranslate.Translators.MicrosoftTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.MicrosoftTranslator.GTranslate.Translators.ITranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)<---

 ---> (Inner Exception #3) System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GTranslate.Translators.YandexTranslator.TranslateAsync(String text, ILanguage toLanguage, ILanguage fromLanguage)
   at GTranslate.Translators.YandexTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.YandexTranslator.GTranslate.Translators.ITranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)<---

 ---> (Inner Exception #4) System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at GTranslate.Translators.BingTranslator.TranslateAsync(String text, ILanguage toLanguage, ILanguage fromLanguage)
   at GTranslate.Translators.BingTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.BingTranslator.GTranslate.Translators.ITranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)
   at GTranslate.Translators.AggregateTranslator.TranslateAsync(String text, String toLanguage, String fromLanguage)<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DictionaryGenerator.modules.TextTranslator.getTranslatedText(String sourceText, String resultLanguage) in C:\Users\mrglaster\Desktop\AMX-Plugins-Translator-main\AMX-Plugins-Translator\modules\TextTranslator.cs:line 36
   at DictionaryGenerator.modules.DictionaryGenerator.generateHarcodelessPlugin() in C:\Users\mrglaster\Desktop\AMX-Plugins-Translator-main\AMX-Plugins-Translator\modules\DictionaryGenerator.cs:line 140
   at DictionaryGenerator.modules.DictionaryGenerator.handlePlugin() in C:\Users\mrglaster\Desktop\AMX-Plugins-Translator-main\AMX-Plugins-Translator\modules\DictionaryGenerator.cs:line 181
   at DictionaryGenerator.Program.Main(String[] args) in C:\Users\mrglaster\Desktop\AMX-Plugins-Translator-main\AMX-Plugins-Translator\Main.cs:line 76

**Comment by tarimren-admin** [comment]
This is the source code of the sma file：

#include <amxmodx>
#include <amxmisc>

enum any:MENU_DATA {MENU_NAME[128], MENU_CMD[64]};

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ CONFIG START ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
#define MENU_TITLE "\r[AWESOMECS.RU]\w Меню сервера"

new const menuData[][MENU_DATA] = {
  {"Информация^n", "say /info"},

  {"Обнулить счёт \r[\yRS\r]", "say /rs"},
  {"Поменять карту \r[\yRTV\r]", "say /rtv"},
  {"Номинировать карту \r[\yMAPS\r]^n", "say /maps"},

  {"Заткнуть игрока \r[\yMUTE\r]", "say /mute"},
  {"Забанить игрока \r[\yVOTEBAN\r]^n", "say /voteban"},

  {"\rАдмины\y онлайн", "say /admins"},

  {"Меню \r[\yVIP\r]", "vipmenu"},
  {"Меню ножей \r[\yVIP\r]", "knifemenu"},
  {"Меню управления \r[\yАдмин\r]", "amxmodmenu"},
  {"Меню возрождений \r[\yСпонсор\r]", "respawnmenu"}
};

new const menuCmds[][] =  {
  "say menu",
  "say_team menu",
  "say /menu",
  "say_team /menu",
  "menu",
  "nightvision"
}

#define ADVERT

#if defined ADVERT
#define ADVERT_TEXT "^3Меню^4 сервера на ^3N^4, или напиши ^3/menu^4 в чат!"
new const Float:ADVERT_INTERVAL = 183.0; // каждые n секунд
#endif
/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ CONFIG END ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */

new menuId;

#if defined ADVERT
const TASK_ADVERT = 87;
#endif

public plugin_init() {
  register_plugin("Server Menu", "1.0", "szawesome");

  BuildMenu();
  
  #if defined ADVERT
    set_task_ex(ADVERT_INTERVAL, "SendAdvertMessage", TASK_ADVERT, .flags = SetTask_Repeat);
  #endif
}

BuildMenu() {
  for(new i = 0; i < sizeof menuCmds; i++) {
    register_clcmd(menuCmds[i], "ShowMenu");
  }

  menuId = menu_create(MENU_TITLE, "menuIdHandler");

  for(new i = 0; i < sizeof menuData; i++) {
    menu_additem(menuId, menuData[i][MENU_NAME], "", 0);
  }

  menu_setprop(menuId, MPROP_BACKNAME, "Назад");
  menu_setprop(menuId, MPROP_NEXTNAME, "Далее");
  menu_setprop(menuId, MPROP_EXITNAME, "Выход");
  menu_setprop(menuId, MPROP_PERPAGE, 7);
  menu_setprop(menuId, MPROP_EXIT, MEXIT_ALL);
  menu_setprop(menuId, MPROP_NUMBER_COLOR, "\w");
}

public menuIdHandler(id, menu, item) {
  if(!is_user_connected(id)) {
    return PLUGIN_HANDLED;
  }

  if(item == MENU_EXIT || item < 0) {
    return PLUGIN_HANDLED;
  }

  new key[sizeof menuData], name[sizeof menuData], access, callback;
  menu_item_getinfo(menu, item, access, key, sizeof key, name, sizeof name, callback);

  client_cmd(id, menuData[item][MENU_CMD]);

  return PLUGIN_HANDLED;
}

public ShowMenu(id) {
  if(!is_user_connected(id)) {
    return PLUGIN_HANDLED;
  }
  return menu_display(id, menuId, 0);
}

#if defined ADVERT
public SendAdvertMessage() {
  client_print_color(0, print_team_default, ADVERT_TEXT);
}
#endif

**Comment by mrglaster** [comment]
I've fixed the problem in this release: https://github.com/mrglaster/AMX-Plugins-Translator/releases/tag/experimental

NOTE: This utility can't help you with this plugin! My translator can't modify defines and hardcoded arrays used in this plugin. And I'm also not sure, that the compiler can compile it. As minimum because  includes here are empty.
